### PR TITLE
Events page

### PR DESCRIPTION
**Pull request by hchoi395**
Added popup functionality on the calendar view that allows users to click on the event to get a popup with all the relevant information.

### CODE REVIEW

**Comment by jonathanvo18** [comment]
The popup idea looks clean. Code looks fine to me

**Review by jonathanvo18 — COMMENTED** [review]
The popup idea looks clean. Code looks fine to me

**Review by Nati-Fekade — APPROVED** [review]
Code looks good and the logic works well.

**Comment by vanto-dev** [comment]
Code looks good. Nice work!

**Pull request merged**
