### PR TITLE
Added some animation effect

### PR DESCRIPTION
**Pull request by Nati-Fekade**
I worked on some animation effect on the home page. This will bring some life into it.

### CODE REVIEW

**Comment by vanto-dev** [comment]
Looks good, the effects make it look really professional!

**Review by vanto-dev — APPROVED** [review]
Looks good! Great job

**Comment by jonathanvo18** [comment]
Nicely done. No issues here.

**Comment by hchoi395** [comment]
Good work so far on the animation effect.

**Pull request merged**
