### PR TITLE
added capabilities to get and add to the FireStore database with fron…

### PR DESCRIPTION
**Pull request by hchoi395**
added new collection on firestore called events. Also added the ability to use the events page user input to get and add to the database. Will work on remove and update later.

### CODE REVIEW

**Review by Nati-Fekade — APPROVED** [review]
Great job Han. Just make sure to remove the commented section on the next PR if it is not necessary.

**Review by bavichugo — APPROVED** [review]
Looks good to me.

**Comment by vanto-dev** [comment]
Great work!

**Comment by jonathanvo18** [comment]
Nice work. No issues here

**Pull request merged**
